# El puerto donde correrá el servidor
server.port=8080

# Esta es la firma secreta para tus tokens (no la compartas)
# Debe ser una cadena larga para evitar errores de seguridad
jwt.secret=EstaEsUnaClaveSecretaMuyLargaYSeguraParaMiPractica2024!
