# El puerto donde correrá el servidor
server.port=8080

# Esta es la firma secreta para tus tokens (no la compartas)
# Debe ser una cadena larga para evitar errores de seguridad
jwt.secret=EstaEsUnaClaveSecretaMuyLargaYSeguraParaMiPractica2024!
# 1. Configuración de la conexión H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Habilitar la consola web (para ver las tablas en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update


# ESTA LÍNEA ES CLAVE:
spring.jpa.defer-datasource-initialization=true